toolbar:
  - styleselect | bold italic | undo redo | bullist numlist outdent indent| forecolor backcolor | fontselect | fontsizeselect | link | emoticons | table | fullscreen
plugins:
  - table
  - fullscreen
  - insertdatetime
  - emoticons
  - link
  - textcolor
theme_advanced_font_sizes:
  - 10px 12px 13px 14px 16px 18px 20px
font_size_style_values:
  - 12px 13px 14px 16px 18px 20px
